# .github/workflows/build.yml
name: Build
on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Package
        run: cd Workflow && zip -r ../CurrencyConverter.alfredworkflow .
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: CurrencyConverter.alfredworkflow
